In [7]:
MUSIC_DATA_PATH = "../data/raw/songs.csv"
USER_DATA_PATH = "../data/raw/users.csv"

In [8]:
import pandas as pd
import numpy as np

In [9]:
music_df = pd.read_csv(MUSIC_DATA_PATH)
user_df = pd.read_csv(USER_DATA_PATH)

In [10]:
music_df

,track_id,duration,release_year,us_popularity_estimate,acousticness,beat_strength,bounciness,danceability,dyn_range_mean,energy,...,time_signature,valence,acoustic_vector_0,acoustic_vector_1,acoustic_vector_2,acoustic_vector_3,acoustic_vector_4,acoustic_vector_5,acoustic_vector_6,acoustic_vector_7
0,t_3c2c29b5-c738-42c0-83e1-ee0e88ac834d,182.293335,1969,99.987810,0.198284,0.336354,0.353215,0.395759,6.443376,0.338417,...,4,0.377411,0.083737,-0.306129,0.045954,0.078400,0.666640,-0.032503,-0.299952,-0.584207
1,t_f48322ca-044e-4069-a797-4fedbbbbb522,237.000000,1980,99.994734,0.362965,0.836106,0.863216,0.922501,13.114539,0.727712,...,4,0.750980,-0.466071,-0.046891,0.344290,0.211617,0.105203,0.111970,-0.133305,0.132393
2,t_5487f622-5641-43da-b263-d8954845d163,365.239990,1971,99.698015,0.287990,0.316192,0.312513,0.284822,5.924984,0.574154,...,4,0.584675,0.038818,-0.342581,0.025039,0.288049,0.571519,-0.177983,-0.124100,-0.582845
3,t_7345e2b8-5f72-440f-a0fc-81bf7e8996f2,295.000000,1976,99.271084,0.545341,0.470771,0.651710,0.703223,11.033814,0.580419,...,4,0.856393,-0.224229,-0.280853,0.184649,0.199369,0.500450,0.065484,-0.360677,-0.224963
4,t_faa63385-9547-4b18-b942-529285cc2ab6,249.293335,1975,99.997719,0.076754,0.404842,0.351039,0.534432,5.741509,0.887209,...,4,0.720318,0.152881,0.231496,0.152248,-0.320413,0.393942,0.161478,-0.090800,-0.225174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20773,t_586d5f58-a2db-4d88-a64b-e6d2a4a98d6c,134.500000,2018,99.835620,0.056739,0.726864,0.724123,0.804991,9.992474,0.523216,...,4,0.210785,-0.943254,0.379621,0.259083,0.108552,-0.328246,-0.038454,-0.524203,0.162012
20774,t_4fa7d39b-5085-4369-9759-401250c93ef1,170.538498,2018,99.999419,0.032032,0.472703,0.514271,0.641779,8.106627,0.562160,...,4,0.176667,-0.786685,0.452118,0.252234,-0.069243,-0.233634,0.078904,-0.485739,0.208814
20775,t_e081f171-8761-484f-a1f9-233b6690e05c,60.000000,2018,99.924688,0.661721,0.615119,0.770913,0.815219,13.444461,0.218947,...,5,0.161503,-0.642718,0.226190,0.330635,0.017866,-0.334436,0.071983,-0.430311,0.006313
20776,t_60e12e04-5a31-40db-9db4-1b43efe6c0eb,190.026672,2018,99.991003,0.372546,0.490898,0.565810,0.683292,8.923687,0.436758,...,4,0.197847,-0.741073,0.316225,0.320096,0.229678,-0.324308,0.144148,0.000750,0.077864
20777,t_395c0c84-fdb3-4b2a-a223-5225770205c8,236.546677,2018,99.968646,0.260546,0.463764,0.551436,0.501953,8.869916,0.639947,...,4,0.113030,-0.900996,0.342353,0.210880,0.094735,-0.292757,-0.034325,-0.553431,0.163369

In [11]:
user_df

,session_id,session_position,session_length,track_id_clean,skip_1,skip_2,skip_3,not_skipped,context_switch,no_pause_before_play,...,long_pause_before_play,hist_user_behavior_n_seekfwd,hist_user_behavior_n_seekback,hist_user_behavior_is_shuffle,hour_of_day,date,premium,context_type,hist_user_behavior_reason_start,hist_user_behavior_reason_end
0,0_00006f66-33e5-4de7-a324-2d18e439fc1e,1,20,t_0479f24c-27d2-46d6-a00c-7ec928f2b539,False,False,False,True,0,0,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone
1,0_00006f66-33e5-4de7-a324-2d18e439fc1e,2,20,t_9099cd7b-c238-47b7-9381-f23f2c1d1043,False,False,False,True,0,1,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone
2,0_00006f66-33e5-4de7-a324-2d18e439fc1e,3,20,t_fc5df5ba-5396-49a7-8b29-35d0d28249e0,False,False,False,True,0,1,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone
3,0_00006f66-33e5-4de7-a324-2d18e439fc1e,4,20,t_23cff8d6-d874-4b20-83dc-94e450e8aa20,False,False,False,True,0,1,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone
4,0_00006f66-33e5-4de7-a324-2d18e439fc1e,5,20,t_64f3743c-f624-46bb-a579-0f3f9a07a123,False,False,False,True,0,1,...,0,0,0,True,16,2018-07-15,True,editorial_playlist,trackdone,trackdone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0_08b98bb8-29ce-44d9-8839-914e31a11044,7,20,t_a323b398-59c8-441d-802a-807c92f0c969,True,True,True,False,0,1,...,0,0,0,True,1,2018-07-15,False,user_collection,fwdbtn,fwdbtn
99996,0_08b98bb8-29ce-44d9-8839-914e31a11044,8,20,t_0c58f726-2f02-47e8-b4d4-3717ff1b06f0,True,True,True,False,0,0,...,1,0,0,True,1,2018-07-15,False,user_collection,fwdbtn,fwdbtn
99997,0_08b98bb8-29ce-44d9-8839-914e31a11044,9,20,t_b0a7549c-e538-4706-8cd7-ac18c7c00e15,True,True,True,False,0,0,...,1,0,0,True,1,2018-07-15,False,user_collection,fwdbtn,fwdbtn
99998,0_08b98bb8-29ce-44d9-8839-914e31a11044,10,20,t_26cd91b7-47aa-42f0-80c2-1667d3e05bc1,True,True,True,False,0,1,...,0,0,0,True,1,2018-07-15,False,user_collection,fwdbtn,fwdbtn
99999,0_08b98bb8-29ce-44d9-8839-914e31a11044,11,20,t_1cafd4e6-da63-4a11-8a83-809df4c3f1a9,False,True,True,False,0,0,...,1,0,0,True,1,2018-07-15,False,user_collection,fwdbtn,fwdbtn